ng install Lucene.Net &
ng install Lucene.Net.Analysis.Common &
::ng install Lucene.Net.Analysis.Kuromoji &
::ng install Lucene.Net.Analysis.Phonetic &
::ng install Lucene.Net.Analysis.SmartCn &
::ng install Lucene.Net.Analysis.Stempel &
::ng install Lucene.Net.Benchmark &
ng install Lucene.Net.Classification &
ng install Lucene.Net.Codecs &
ng install Lucene.Net.Expressions &
ng install Lucene.Net.Facet &
ng install Lucene.Net.Grouping &
ng install Lucene.Net.Highlighter &
::ng install Lucene.Net.ICU &
ng install Lucene.Net.Join &
ng install Lucene.Net.Memory &
ng install Lucene.Net.Misc &
ng install Lucene.Net.Queries &
ng install Lucene.Net.QueryParser &
::ng install Lucene.Net.Replicator &
ng install Lucene.Net.Sandbox &
ng install Lucene.Net.Spatial &
ng install Lucene.Net.Suggest